### ISSUE TITLE
Documentation on how to add a new URL/website

### ISSUE THREAD

**Issue by cuducos** [jystewart/covid19-response-screenshots#3]
Hi all,

Congrats, very interesting project : )

I’m part of a team working close to one of Mozambique‘s government website focused on COVID-19 response. In this process, we redesigned their prototype and we would like to generate a report including the current site (public at covid19.ins.gov.mz) and the new one (running on a private URL at the moment, before the official launch).

I added the Lighthouse HTML and JSON files to the `lighthouse-reports/` directory and the URLs to the `list.csv`. Now the `generate-report.py` is able to find it: it is included in `lighthous_index` and the script runs without errors. I added the screenshots to the date folder, but not sure if that was the idea.

However, the reports are empty:

![image](https://user-images.githubusercontent.com/4732915/84939820-e7521080-b0ac-11ea-96bc-a579bd8d2fbd.png)

Can I help with enhancing the documentation? I mean, I am happy yo help, but I might need some support. If I can run this for my use case, I can open a PR generalizing _how to include another URL_ in the package.

What do you think about it?

**Comment by jystewart** [comment]
Hi @cuducos - thanks for the feedback

I've just added a note to the README about adding URLs.

The content of the lighthouse-reports and dated folders are generated from running the scripts on  a server we manage and are then pushed up here. If we decide to keep some version of this running long term there's some work to improve the architecture of that!

For now, the best thing is either to email me, or submit a pull request to add the URL to list.csv and then the scripts will start picking up the site the following day.

**Comment by cuducos** [comment]
Ok, so, in a nut-shell, there is still no information for us no run the project on non-public URLs, am I right? Nor there is interest in helping me setting this up and sharing back with the project, correct?

Sorry if these questions sound blunt, that is not the idea. I just want to be clear about whether what I asked (how to reproduce the project locally) is of any interest for the project before I take this further…
